In [63]:
import random
def random_num(start, end):
    return random.randint(start, end)

In [64]:
import numpy as np


class Individual:
    # create a 'genome' of weights and biases for each layer
    def __init__(self, num_inputLayer, num_outputLayer, *num_hiddenLayers):
        self.num_layers = len(num_hiddenLayers) + 2
        self.species = [num_inputLayer, num_outputLayer, *num_hiddenLayers]

        self.input_weights = np.random.rand(num_inputLayer)
        self.output_weights = np.random.rand(num_outputLayer)
        self.hidden_weights = []
        for num_hiddenLayer in num_hiddenLayers:
            self.hidden_weights.append(np.random.rand(num_hiddenLayer))
        
        self.input_bias = np.random.rand(num_inputLayer)
        self.output_bias = np.random.rand(num_outputLayer)
        self.hidden_bias = []
        for num_hiddenLayer in num_hiddenLayers:
            self.hidden_bias.append(np.random.rand(num_hiddenLayer))

        self.fitness = self.cal_fitness()
    
    def cal_fitness(self):
        # play game with genome
        return 0

    def mate(self, other):
        pass

    def __lt__(selection, other):
        return selection.fitness < other.fitness

    def mutate(self):
        # choose a random layer
        layer = random_num(0, self.num_layers-1)
        print(f'mutated layer: {layer}')
        
        random_float = random.uniform(-1, 1)
        print(random_float)
        
        
        if layer == 0:
            # input layer
            num_inputLayer = len(self.input_weights)
            gene = random_num(0, num_inputLayer-1)
            self.input_weights[gene] += random_float
        elif layer == self.num_layers-1:
            # output layer
            num_outputLayer = len(self.output_weights)
            gene = random_num(0, num_outputLayer-1)
            self.output_weights[gene] += random_float
        else:
            # hidden layer
            num_hiddenLayer = len(self.hidden_weights[layer-1])
            gene = random_num(0, num_hiddenLayer-1)
            self.hidden_weights[layer-1][gene] += random_float
    
    def print_genome(self):
        print(self.input_weights)
        print(self.output_weights)
        print(self.hidden_weights)
        print(self.input_bias)
        print(self.output_bias)
        print(self.hidden_bias)

    def mate(self, other):
        if self.species != other.species:
            print("Species do not match!")
            return None

        child = Individual(*self.species)
        child.create_gnome(*self.species)  # Correctly unpack self.species
        
        # crossover input weights
        child.input_weights = np.array([
            self.input_weights[i] if random.random() < 0.45 else 
            other.input_weights[i] if random.random() < 0.90 else 
            random.uniform(-1, 1)
            for i in range(len(self.input_weights))
        ])
        
        # crossover input biases
        child.input_bias = np.array([
            self.input_bias[i] if random.random() < 0.45 else 
            other.input_bias[i] if random.random() < 0.90 else 
            random.uniform(-1, 1)
            for i in range(len(self.input_bias))
        ])

        # crossover output weights
        child.output_weights = np.array([
            self.output_weights[i] if random.random() < 0.45 else 
            other.output_weights[i] if random.random() < 0.90 else 
            random.uniform(-1, 1)
            for i in range(len(self.output_weights))
        ])
        
        # crossover output biases
        child.output_bias = np.array([
            self.output_bias[i] if random.random() < 0.45 else 
            other.output_bias[i] if random.random() < 0.90 else 
            random.uniform(-1, 1)
            for i in range(len(self.output_bias))
        ])

        # handle hidden layers weights
        child.hidden_weights = []
        for i in range(len(self.hidden_weights)):
            child.hidden_weights.append(np.array([
                self.hidden_weights[i][j] if random.random() < 0.45 else 
                other.hidden_weights[i][j] if random.random() < 0.90 else 
                random.uniform(-1, 1)
                for j in range(len(self.hidden_weights[i]))
            ]))
        
        # handle hidden layers weights
        child.hidden_bias = []
        for i in range(len(self.hidden_bias)):
            child.hidden_bias.append(np.array([
                self.hidden_bias[i][j] if random.random() < 0.45 else 
                other.hidden_bias[i][j] if random.random() < 0.90 else 
                random.uniform(-1, 1)
                for j in range(len(self.hidden_bias[i]))
            ]))
            
        return child

In [65]:
genetics = Genetics()

genetics.create_gnome(16, 4, 16, 16)

genetics.print_genome()

genetics.mutate()
print("mutated\n\n")
genetics.print_genome()


[0.79671987 0.55078679 0.00683371 0.66886218 0.78475299 0.71404704
 0.36740474 0.34699778 0.52848971 0.27080919 0.07923693 0.0076409
 0.73814202 0.89278228 0.67178853 0.20470331]
[0.43734229 0.18062557 0.17982941 0.44432361]
[array([0.22088481, 0.62745942, 0.75597054, 0.27770484, 0.57337054,
       0.04960939, 0.65904527, 0.88000336, 0.34519241, 0.66777478,
       0.43725011, 0.56751067, 0.73126646, 0.18841854, 0.5241345 ,
       0.33084756]), array([0.77963823, 0.25348115, 0.60419389, 0.46262572, 0.52081482,
       0.90844839, 0.97965215, 0.90586139, 0.60406103, 0.47017668,
       0.52331809, 0.93948247, 0.4633681 , 0.63866754, 0.71692483,
       0.25438691])]
[0.97797072 0.58134636 0.02764225 0.12862173 0.1225786  0.16312139
 0.17356625 0.88013793 0.61243252 0.62853016 0.9619545  0.8426268
 0.38914289 0.67766189 0.45413144 0.10854151]
[0.36805123 0.84614593 0.16973125 0.10686119]
[array([0.93708986, 0.60935617, 0.30723679, 0.08234581, 0.51711371,
       0.183137  , 0.70323182, 0.7215

In [66]:
# create 100 genomes

genomes = []
for _ in range(100):
    genome = Genetics()
    genome.create_gnome(16, 4, 16, 16)
    genomes.append(genome)

In [67]:
genomes[0].print_genome()

[0.69095802 0.66187764 0.19924409 0.63833206 0.11785453 0.66651085
 0.14687571 0.52160132 0.28592199 0.19632071 0.7473711  0.98936345
 0.21605392 0.22472184 0.59062909 0.41141754]
[0.05322611 0.8703947  0.04748606 0.82382457]
[array([0.4444465 , 0.71834272, 0.46228118, 0.1366286 , 0.06557762,
       0.24949354, 0.02312261, 0.44135579, 0.55883077, 0.71950249,
       0.08239654, 0.67940883, 0.41793963, 0.10568672, 0.49151934,
       0.98024501]), array([0.42246168, 0.5648815 , 0.47127603, 0.26119308, 0.52168482,
       0.2507569 , 0.69676335, 0.14176143, 0.32577444, 0.80002495,
       0.41941433, 0.6509901 , 0.21563595, 0.79266085, 0.79651479,
       0.63939555])]
[0.34382522 0.07821782 0.79832939 0.3653068  0.09000605 0.44326925
 0.27324857 0.79142673 0.33124653 0.97717981 0.04027014 0.40958771
 0.69145055 0.97389645 0.02211474 0.98726123]
[0.25512913 0.19825599 0.11224662 0.52616588]
[array([0.25239262, 0.95895519, 0.11112356, 0.64674566, 0.35075922,
       0.15008678, 0.98017513, 0.96

In [68]:
genomes[1].print_genome()

[0.85251574 0.42658011 0.89723399 0.52156658 0.87247488 0.20227732
 0.89649466 0.45498488 0.83270484 0.1748593  0.53832557 0.76119474
 0.72054818 0.30188788 0.03235205 0.35233016]
[0.49355893 0.12951876 0.42459899 0.10645877]
[array([0.18847534, 0.40300693, 0.20301284, 0.35000065, 0.46136769,
       0.00859702, 0.35069829, 0.73455941, 0.05116665, 0.72883245,
       0.12321641, 0.43886188, 0.76338612, 0.42367224, 0.83972667,
       0.49211144]), array([0.15355541, 0.0766696 , 0.42711578, 0.97306885, 0.97216032,
       0.11397252, 0.37872418, 0.20026245, 0.19205569, 0.32660949,
       0.46795478, 0.32311953, 0.90429177, 0.75942846, 0.7302066 ,
       0.71985156])]
[0.840992   0.92551878 0.18918685 0.96002455 0.73588133 0.21970629
 0.07104653 0.34634776 0.16352651 0.83262643 0.57636164 0.97685424
 0.14610044 0.16687672 0.71967878 0.5814511 ]
[0.58494459 0.81184142 0.08315205 0.58451236]
[array([0.82608163, 0.26589326, 0.28971787, 0.99328507, 0.87837401,
       0.59369139, 0.4034676 , 0.25

In [69]:
genomes[0].mate(genomes[1]).print_genome()

[0.69095802 0.66187764 0.19924409 0.63833206 0.11785453 0.66651085
 0.14687571 0.45498488 0.83270484 0.1748593  0.7473711  0.98936345
 0.72054818 0.30188788 0.03235205 0.35233016]
[0.05322611 0.12951876 0.42459899 0.82382457]
[array([ 0.4444465 ,  0.71834272,  0.46228118,  0.1366286 ,  0.06557762,
        0.00859702,  0.02312261,  0.73455941,  0.05116665,  0.71950249,
        0.12321641, -0.23811209,  0.41793963,  0.42367224,  0.49151934,
        0.49211144]), array([0.42246168, 0.0766696 , 0.47127603, 0.97306885, 0.97216032,
       0.2507569 , 0.69676335, 0.20026245, 0.32577444, 0.32660949,
       0.46795478, 0.32311953, 0.21563595, 0.75942846, 0.79651479,
       0.71985156])]
[0.840992   0.92551878 0.79832939 0.3653068  0.73588133 0.44326925
 0.07104653 0.34634776 0.16352651 0.97717981 0.04027014 0.97685424
 0.69145055 0.16687672 0.71967878 0.5814511 ]
[0.25512913 0.19825599 0.08315205 0.58451236]
[array([ 0.82608163,  0.95895519,  0.28971787,  0.99328507,  0.87837401,
        0.1500

In [76]:
class Population:
    def __init__(self, population_size):
        self.generation_num = 0
        self.population = []
        
        
        for _ in range(population_size):
            self.population.append(Individual(16, 4, 16, 16))

    def sort_population(self):
        self.population = sorted(self.population)[::-1]

In [80]:
p = Population(20)

p.population[0].fitness = 10
p.population[1].fitness = 5
p.population[10].fitness = 15
p.sort_population()